# Generated by Django 4.1 on 2023-02-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
