# Generated by Django 4.1 on 2023-02-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_day_alter_appointment_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_name',
            field=models.CharField(max_length=50),
        ),
    ]
