# Generated by Django 4.1 on 2023-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_rename_booking_name_appointment_booking_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_user_id',
            field=models.IntegerField(),
        ),
    ]
