# Generated by Django 4.1 on 2023-02-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_happened'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
