# Generated by Django 4.1 on 2023-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.CharField(choices=[('9:00', 9), ('10:00', 10), ('11:00', 11)], max_length=5),
        ),
    ]
